'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
    en: {
        // Header
        'massage.platform': 'Massage Platform',
        'dashboard': 'Dashboard',
        'services': 'Services',
        'manage.services': 'Manage Services',
        'login': 'Login',
        'sign.out': 'Sign Out',
        'welcome.back': 'Welcome back',

        // Homepage
        'find.perfect.massage': 'Find Your Perfect Massage',
        'discover.therapists': 'Discover professional massage therapists and book your relaxation session today. From Swedish to Deep Tissue, find the perfect treatment for your needs.',
        'browse.services': 'Browse Services',
        'sign.in': 'Sign In',
        'get.started': 'Get Started',
        'why.choose.us': 'Why Choose Us',
        'why.choose.us.subtitle': 'Experience the difference with our premium massage therapy services',
        'professional.therapists': 'Professional Therapists',
        'licensed.experienced': 'Licensed & Experienced',
        'flexible.scheduling': 'Flexible Scheduling',
        'book.anytime': 'Book Anytime',
        'quality.guaranteed': 'Quality Guaranteed',
        'satisfaction.assured': 'Satisfaction Assured',
        'available.services': 'Available Services',
        'search.placeholder': 'Search for massage services...',
        'book.now': 'Book Now',
        'learn.more': 'Learn More',

        // Services
        'our.massage.services': 'Our Services',
        'discover.therapies': 'Discover a wide range of professional services designed to help you relax, heal, and rejuvenate',
        'search.services': 'Search for services...',
        'category': 'Category',
        'all.categories': 'All Categories',
        'price.range': 'Price Range',
        'all.prices': 'All Prices',
        'under.50': 'Under $50',
        '50.100': '$50 - $100',
        '100.150': '$100 - $150',
        'over.150': 'Over $150',
        'services.found': 'services found',
        'no.services': 'No services found',
        'try.adjusting': 'Try adjusting your search criteria or browse all categories',
        'clear.filters': 'Clear Filters',
        'sign.in.to.book': 'Sign In to Book',

        // Dashboard
        'welcome.back.name': 'Welcome back, {name}!',
        'manage.services.appointments': 'Manage your services and appointments',
        'view.appointments.history': 'View your upcoming appointments and booking history',
        'upcoming.appointments': 'Upcoming Appointments',
        'past.appointments': 'Past Appointments',
        'my.services': 'My Services',
        'book.new.appointment': 'Book New Appointment',
        'no.upcoming.appointments': 'No upcoming appointments',
        'ready.to.relax': 'Ready to relax? Book your next session.',
        'no.upcoming.scheduled': 'No upcoming appointments scheduled.',
        'no.past.appointments': 'No past appointments',
        'no.services.yet': 'No services yet',
        'start.adding.service': 'Start by adding your first service to attract customers',
        'post.new.service': 'Post New Service',
        'service.dashboard': 'Service Dashboard',
        'quick.actions': 'Quick Actions',
        'recent.services': 'Recent Services',
        'total.services': 'Total Services',
        'active.services': 'Active Services',
        'inactive.services': 'Inactive Services',
        'view.all.services': 'View All Services',

        // Manage Services
        'manage.your.services': 'Manage Your Services',
        'back.to.dashboard': 'Back to Dashboard',
        'services.available': 'services available',
        'edit.service': 'Edit Service',
        'service.name': 'Service Name',
        'description': 'Description',
        'duration.minutes': 'Duration (minutes)',
        'price': 'Price ($)',
        'category': 'Category',
        'image.url.optional': 'Image URL (optional)',
        'service.active.visible': 'Service is active and visible to customers',
        'cancel': 'Cancel',
        'update.service': 'Update Service',
        'add.service': 'Add Service',
        'active': 'Active',
        'inactive': 'Inactive',
        'min': 'min',
        'upload.image': 'Upload Image',
        'drag.drop.image': 'Drag & drop an image here, or click to select',
        'image.preview': 'Image Preview',
        'service.details': 'Service Details',

        // Onboarding
        'welcome.to.aura': '✨ Welcome to AURA ✨',
        'join.thousands.professionals': '🚀 Join thousands of wellness professionals and start your journey to success!',
        'complete.profile.steps': 'Complete your profile in just a few steps',
        'your.foundation': 'Your Foundation',
        'your.professional.showcase': 'Your Professional Showcase',
        'your.practice': 'Your Practice',
        'personal.details': 'Personal Details',
        'foundation.description': 'Let\'s start with your basic information to create your account and establish your foundation on our platform.',
        'professional.showcase.description': 'Build your public-facing professional profile to attract clients and showcase your expertise.',
        'practice.description': 'Define the logistical details for client bookings and payments.',
        'full.name': 'Full Name',
        'email.address': 'Email Address',
        'phone.number': 'Phone Number',
        'password': 'Password',
        'confirm.password': 'Confirm Password',
        'professional.title': 'Professional Title',
        'about.me': 'About Me',
        'primary.service.city': 'Primary Service City',
        'service.areas': 'Service Areas',
        'pricing.for.services': 'Pricing for Services',
        'weekly.availability': 'Weekly Availability',
        'profile.picture': 'Profile Picture',
        'upload.profile.picture': 'Upload Profile Picture',
        'drag.drop.profile': 'Drag & drop your profile picture here, or click to select',
        'services.offered': 'Services Offered',
        'select.services': 'Select the services you offer',
        'add.service.area': 'Add Service Area',
        'type.and.press.enter': 'Type and press Enter to add',
        'price.cop': 'Price (COP)',
        'monday': 'Monday',
        'tuesday': 'Tuesday',
        'wednesday': 'Wednesday',
        'thursday': 'Thursday',
        'friday': 'Friday',
        'saturday': 'Saturday',
        'sunday': 'Sunday',
        'morning': 'Morning (8AM - 12PM)',
        'afternoon': 'Afternoon (12PM - 5PM)',
        'evening': 'Evening (5PM - 9PM)',

        'create.account': 'Create Account',
        'add.more.info': 'Add More Info',
        'complete.onboarding': 'Complete Onboarding',
        'creating.account': 'Creating Account...',
        'partner.account.created': 'Partner account created successfully! Redirecting to dashboard...',
        'partner.profile.updated': 'Partner profile updated successfully! Redirecting to dashboard...',
        'account.creation.failed': 'Account creation failed. Please try again.',
        'validation.fullname.required': 'Full Name is required',
        'validation.fullname.min': 'Full Name must be at least 2 characters',
        'validation.email.required': 'Email is required',
        'validation.email.invalid': 'Please enter a valid email address',
        'validation.phone.required': 'Phone number is required',
        'validation.phone.invalid': 'Please enter a valid phone number',
        'validation.password.required': 'Password is required',
        'validation.password.min': 'Password must be at least 6 characters',
        'validation.confirmpassword.required': 'Please confirm your password',
        'validation.confirmpassword.mismatch': 'Passwords do not match',
        'validation.professionaltitle.required': 'Professional Title is required',
        'validation.aboutme.required': 'About Me is required',
        'validation.aboutme.min': 'About Me must be at least 50 characters',
        'validation.services.required': 'Please select at least one service',
        'validation.city.required': 'Primary service city is required',
        'validation.areas.required': 'Please add at least one service area',
        'validation.pricing.required': 'Please set pricing for all selected services',
        'validation.availability.required': 'Please select at least one time slot',
        'placeholder.full.name': 'Enter your full name',
        'placeholder.email': 'Enter your email address',
        'placeholder.phone': 'Enter your phone number',
        'placeholder.password': 'Enter your password',
        'placeholder.confirm.password': 'Confirm your password',
        'placeholder.professional.title': 'e.g., Licensed Massage Therapist, Wellness Specialist',
        'placeholder.about.me': 'Tell clients about your experience, specialties, and approach to wellness...',
        'placeholder.city': 'e.g., Bogotá, Medellín, Cali',
        'pricing.duration': 'Pricing & Duration',
        'visibility.settings': 'Visibility Settings',
        'save.service': 'Save Service',
        'service.saved': 'Service saved successfully!',
        'error.saving': 'Error saving service',

        // Book Appointment
        'book.appointment': 'Book Appointment',
        'back.to.services': 'Back to Services',
        'select.date.time': 'Select Date & Time',
        'review.confirm': 'Review & Confirm',
        'booking.complete': 'Booking Complete',
        'choose.date': 'Choose Date',
        'choose.time': 'Choose Time',
        'please.select.date': 'Please select a date first',
        'special.requests.notes': 'Special Requests or Notes (optional)',
        'special.requests.placeholder': 'Any special requests, allergies, or notes for your therapist...',
        'review.booking': 'Review Your Booking',
        'per.session': 'per session',
        'booking.confirmed': 'Booking Confirmed!',
        'appointment.booked': 'Your appointment has been successfully booked. You will receive a confirmation email shortly.',
        'view.appointments': 'View My Appointments',
        'next': 'Next',
        'back': 'Back',
        'confirm.booking': 'Confirm Booking',
        'booking': 'Booking...',

        // Common
        'all': 'All',
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',
        'save': 'Save',
        'delete': 'Delete',
        'edit': 'Edit',
        'close': 'Close',
        'submit': 'Submit',
        'yes': 'Yes',
        'no': 'No',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'are.you.sure': 'Are you sure?',
        'failed.to.load': 'Failed to load',
        'no.data': 'No data available',
    },
    es: {
        // Header
        'massage.platform': 'Plataforma de Masajes',
        'dashboard': 'Panel',
        'services': 'Servicios',
        'manage.services': 'Gestionar Servicios',
        'login': 'Iniciar Sesión',
        'sign.out': 'Cerrar Sesión',
        'welcome.back': 'Bienvenido de vuelta',

        // Homepage
        'find.perfect.massage': 'Encuentra Tu Masaje Perfecto',
        'discover.therapists': 'Descubre terapeutas profesionales de masajes y reserva tu sesión de relajación hoy. Desde Sueco hasta Tejido Profundo, encuentra el tratamiento perfecto para tus necesidades.',
        'browse.services': 'Explorar Servicios',
        'sign.in': 'Iniciar Sesión',
        'get.started': 'Comenzar',
        'why.choose.us': '¿Por Qué Elegirnos?',
        'why.choose.us.subtitle': 'Experimenta la diferencia con nuestros servicios de masoterapia premium',
        'professional.therapists': 'Terapeutas Profesionales',
        'licensed.experienced': 'Licenciados y Experimentados',
        'flexible.scheduling': 'Horarios Flexibles',
        'book.anytime': 'Reservar en cualquier momento',
        'quality.guaranteed': 'Calidad Garantizada',
        'satisfaction.assured': 'Satisfacción Garantizada',
        'available.services': 'Servicios Disponibles',
        'search.placeholder': 'Buscar servicios de masaje...',
        'book.now': 'Reservar Ahora',
        'learn.more': 'Saber Más',

        // Services
        'our.massage.services': 'Nuestros Servicios',
        'discover.therapies': 'Descubre una amplia gama de servicios profesionales diseñados para ayudarte a relajarte, curar y rejuvenecer',
        'search.services': 'Buscar servicios...',
        'category': 'Categoría',
        'all.categories': 'Todas las Categorías',
        'price.range': 'Rango de Precio',
        'all.prices': 'Todos los Precios',
        'under.50': 'Menos de $50',
        '50.100': '$50 - $100',
        '100.150': '$100 - $150',
        'over.150': 'Más de $150',
        'services.found': 'servicios encontrados',
        'no.services': 'No se encontraron servicios',
        'try.adjusting': 'Intenta ajustar tus criterios de búsqueda o explorar todas las categorías',
        'clear.filters': 'Limpiar Filtros',
        'sign.in.to.book': 'Inicia Sesión para Reservar',

        // Dashboard
        'welcome.back.name': '¡Bienvenido de vuelta, {name}!',
        'manage.services.appointments': 'Gestiona tus servicios y citas',
        'view.appointments.history': 'Ve tus próximas citas y historial de reservas',
        'upcoming.appointments': 'Próximas Citas',
        'past.appointments': 'Citas Pasadas',
        'my.services': 'Mis Servicios',
        'book.new.appointment': 'Reservar Nueva Cita',
        'no.upcoming.appointments': 'No hay próximas citas',
        'ready.to.relax': '¿Listo para relajarte? Reserva tu próxima sesión.',
        'no.upcoming.scheduled': 'No hay próximas citas programadas.',
        'browse.services': 'Explorar Servicios',
        'no.past.appointments': 'No hay citas pasadas',
        'no.services.yet': 'Aún no hay servicios',
        'start.adding.service': 'Comienza agregando tu primer servicio para atraer clientes',
        'add.first.service': 'Agregar Tu Primer Servicio',
        'manage.services': 'Gestionar Servicios',
        'post.new.service': 'Publicar Nuevo Servicio',
        'service.dashboard': 'Panel de Servicios',
        'quick.actions': 'Acciones Rápidas',
        'recent.services': 'Servicios Recientes',
        'total.services': 'Total de Servicios',
        'active.services': 'Servicios Activos',
        'inactive.services': 'Servicios Inactivos',
        'view.all.services': 'Ver Todos los Servicios',

        // Manage Services
        'manage.your.services': 'Gestionar Tus Servicios',
        'back.to.dashboard': 'Volver al Panel',
        'services.available': 'servicios disponibles',
        'add.new.service': 'Agregar Nuevo Servicio',
        'add.first.service': 'Agregar Tu Primer Servicio',
        'edit.service': 'Editar Servicio',
        'add.new.service': 'Agregar Nuevo Servicio',
        'service.name': 'Nombre del Servicio',
        'description': 'Descripción',
        'duration.minutes': 'Duración (minutos)',
        'price': 'Precio ($)',
        'category': 'Categoría',
        'image.url.optional': 'URL de Imagen (opcional)',
        'service.active.visible': 'El servicio está activo y visible para los clientes',
        'cancel': 'Cancelar',
        'update.service': 'Actualizar Servicio',
        'add.service': 'Agregar Servicio',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'min': 'min',
        'upload.image': 'Subir Imagen',
        'drag.drop.image': 'Arrastra y suelta una imagen aquí, o haz clic para seleccionar',
        'image.preview': 'Vista Previa de Imagen',
        'service.details': 'Detalles del Servicio',
        'pricing.duration': 'Precio y Duración',
        'visibility.settings': 'Configuración de Visibilidad',
        'save.service': 'Guardar Servicio',
        'service.saved': '¡Servicio guardado exitosamente!',
        'error.saving': 'Error al guardar el servicio',

        // Book Appointment
        'book.appointment': 'Reservar Cita',
        'back.to.services': 'Volver a Servicios',
        'select.date.time': 'Seleccionar Fecha y Hora',
        'review.confirm': 'Revisar y Confirmar',
        'booking.complete': 'Reserva Completada',
        'choose.date': 'Elegir Fecha',
        'choose.time': 'Elegir Hora',
        'please.select.date': 'Por favor selecciona una fecha primero',
        'special.requests.notes': 'Solicitudes Especiales o Notas (opcional)',
        'special.requests.placeholder': 'Cualquier solicitud especial, alergias o notas para tu terapeuta...',
        'review.booking': 'Revisar Tu Reserva',
        'per.session': 'por sesión',
        'booking.confirmed': '¡Reserva Confirmada!',
        'appointment.booked': 'Tu cita ha sido reservada exitosamente. Recibirás un correo de confirmación pronto.',
        'view.appointments': 'Ver Mis Citas',
        'next': 'Siguiente',
        'back': 'Atrás',
        'confirm.booking': 'Confirmar Reserva',
        'booking': 'Reservando...',

        // Common
        'all': 'Todos',
        'loading': 'Cargando...',
        'error': 'Error',
        'success': 'Éxito',
        'save': 'Guardar',
        'delete': 'Eliminar',
        'edit': 'Editar',
        'close': 'Cerrar',
        'submit': 'Enviar',
        'yes': 'Sí',
        'no': 'No',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'are.you.sure': '¿Estás seguro?',
        'failed.to.load': 'Error al cargar',
        'no.data': 'No hay datos disponibles',

        // Onboarding
        'welcome.to.aura': '✨ ¡Bienvenido a AURA ✨',
        'join.thousands.professionals': '🚀 ¡Únete a miles de profesionales del bienestar y comienza tu camino al éxito!',
        'complete.profile.steps': 'Completa tu perfil en solo unos pasos',
        'your.foundation': 'Tu Fundación',
        'your.professional.showcase': 'Tu Vitrina Profesional',
        'your.practice': 'Tu Práctica',
        'personal.details': 'Detalles Personales',
        'foundation.description': 'Comencemos con tu información básica para crear tu cuenta y establecer tu fundación en nuestra plataforma.',
        'professional.showcase.description': 'Construye tu perfil profesional público para atraer clientes y mostrar tu experiencia.',
        'practice.description': 'Define los detalles logísticos para las reservas de clientes y pagos.',
        'full.name': 'Nombre Completo',
        'email.address': 'Correo Electrónico',
        'phone.number': 'Número de Teléfono',
        'password': 'Contraseña',
        'confirm.password': 'Confirmar Contraseña',
        'professional.title': 'Título Profesional',
        'about.me': 'Acerca de Mí',
        'primary.service.city': 'Ciudad Principal de Servicio',
        'service.areas': 'Áreas de Servicio',
        'pricing.for.services': 'Precios por Servicios',
        'weekly.availability': 'Disponibilidad Semanal',
        'profile.picture': 'Foto de Perfil',
        'upload.profile.picture': 'Subir Foto de Perfil',
        'drag.drop.profile': 'Arrastra y suelta tu foto de perfil aquí, o haz clic para seleccionar',
        'services.offered': 'Servicios Ofrecidos',
        'select.services': 'Selecciona los servicios que ofreces',
        'add.service.area': 'Agregar Área de Servicio',
        'type.and.press.enter': 'Escribe y presiona Enter para agregar',
        'price.cop': 'Precio (COP)',
        'monday': 'Lunes',
        'tuesday': 'Martes',
        'wednesday': 'Miércoles',
        'thursday': 'Jueves',
        'friday': 'Viernes',
        'saturday': 'Sábado',
        'sunday': 'Domingo',
        'morning': 'Mañana (8AM - 12PM)',
        'afternoon': 'Tarde (12PM - 5PM)',
        'evening': 'Noche (5PM - 9PM)',
        'back': 'Atrás',
        'next': 'Siguiente',
        'create.account': 'Crear Cuenta',
        'add.more.info': 'Agregar Más Información',
        'complete.onboarding': 'Completar Registro',
        'creating.account': 'Creando Cuenta...',
        'partner.account.created': '¡Cuenta de socio creada exitosamente! Redirigiendo al panel...',
        'partner.profile.updated': '¡Perfil de socio actualizado exitosamente! Redirigiendo al panel...',
        'account.creation.failed': 'Error al crear la cuenta. Por favor intenta de nuevo.',
        'validation.fullname.required': 'El nombre completo es requerido',
        'validation.fullname.min': 'El nombre completo debe tener al menos 2 caracteres',
        'validation.email.required': 'El correo electrónico es requerido',
        'validation.email.invalid': 'Por favor ingresa un correo electrónico válido',
        'validation.phone.required': 'El número de teléfono es requerido',
        'validation.phone.invalid': 'Por favor ingresa un número de teléfono válido',
        'validation.password.required': 'La contraseña es requerida',
        'validation.password.min': 'La contraseña debe tener al menos 6 caracteres',
        'validation.confirmpassword.required': 'Por favor confirma tu contraseña',
        'validation.confirmpassword.mismatch': 'Las contraseñas no coinciden',
        'validation.professionaltitle.required': 'El título profesional es requerido',
        'validation.aboutme.required': 'Acerca de mí es requerido',
        'validation.aboutme.min': 'Acerca de mí debe tener al menos 50 caracteres',
        'validation.services.required': 'Por favor selecciona al menos un servicio',
        'validation.city.required': 'La ciudad principal de servicio es requerida',
        'validation.areas.required': 'Por favor agrega al menos un área de servicio',
        'validation.pricing.required': 'Por favor establece precios para todos los servicios seleccionados',
        'validation.availability.required': 'Por favor selecciona al menos un horario',
        'placeholder.full.name': 'Ingresa tu nombre completo',
        'placeholder.email': 'Ingresa tu correo electrónico',
        'placeholder.phone': 'Ingresa tu número de teléfono',
        'placeholder.password': 'Ingresa tu contraseña',
        'placeholder.confirm.password': 'Confirma tu contraseña',
        'placeholder.professional.title': 'ej., Terapeuta de Masajes Licenciado, Especialista en Bienestar',
        'placeholder.about.me': 'Cuéntales a los clientes sobre tu experiencia, especialidades y enfoque al bienestar...',
        'placeholder.city': 'ej., Bogotá, Medellín, Cali',
    }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string, params?: Record<string, string>) => {
        const translation = translations[language][key as keyof typeof translations[typeof language]] || key;

        if (params) {
            return Object.entries(params).reduce((str, [param, value]) => {
                return str.replace(`{${param}}`, value);
            }, translation);
        }

        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
